/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sumajni3_Native */

#ifndef _Included_com_example_sumajni3_Native
#define _Included_com_example_sumajni3_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sumajni3_Native
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_sumajni3_Native_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
