/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pruba3jni_LedManager */

#ifndef _Included_com_example_pruba3jni_LedManager
#define _Included_com_example_pruba3jni_LedManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pruba3jni_LedManager
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_pruba3jni_LedManager_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
